// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4KDc9OSxz7rFew4buX13u44NC6GaRHQQ',
    appId: '1:345519256458:web:f1a420ac8b2385cf058e73',
    messagingSenderId: '345519256458',
    projectId: 't2024cs3-campuslostandfound',
    authDomain: 't2024cs3-campuslostandfound.firebaseapp.com',
    storageBucket: 't2024cs3-campuslostandfound.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3-SRYFk2cCfDEVMMXzQ2OpemLJH7b6I',
    appId: '1:345519256458:android:7e2f77c5e52578cb058e73',
    messagingSenderId: '345519256458',
    projectId: 't2024cs3-campuslostandfound',
    storageBucket: 't2024cs3-campuslostandfound.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKFoftUBhazsHcYxP_mwteCSK6gyUYrhc',
    appId: '1:345519256458:ios:f9d59b80d629b6f1058e73',
    messagingSenderId: '345519256458',
    projectId: 't2024cs3-campuslostandfound',
    storageBucket: 't2024cs3-campuslostandfound.firebasestorage.app',
    iosClientId:
        '345519256458-fucj5o7je1nqihh8sh9fs140jvn9ov94.apps.googleusercontent.com',
    iosBundleId: 'com.example.campuslostandfound',
  );
}
